# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Select XCode
    - run: sudo xcode-select -switch /Applcations/Xcode.app
    
    - name: Build and Test the App
    - run: xcodebuild cleanbuild test -workspace QuizApp/QuizApp.xcworkspace -scheme
    - name: Run tests
    - run: swift test -v
