# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Select XCode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
    
    - name: Build and Test the App
      run: xcodebuild clean build test -workspace QuizforApp.xcworkspace -scheme "QuizforApp" -sdk iphonesimulator -destination "platform:iOS Simulator, id:72A177E7-6329-4DF7-ACCA-085F1FFB5AD6, OS:16.2, name:iPhone SE (3rd generation)" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

    - name: Run tests
      run: swift test -v
